...

diff --git a/lib/default/util b/lib/default/util
--- a/lib/default/util
+++ b/lib/default/util
@@ -1,12 +1,17 @@
 
 ___x_cmd_ws___exe_default_pull(){
-    :
+    git pull origin "$(git rev-parse --abbrev-ref HEAD)"
 }
 
 ___x_cmd_ws___exe_default_push(){
-    ___x_cmd_ws___exe_default_pull && ___x_cmd_ws___exe_default_push
+    if ! ___x_cmd_ws___exe_default_pull; then
+        ws:error "Fail to pull"
+        return 1
+    fi
+
+    git push origin "${1:-"$(git rev-parse --abbrev-ref HEAD)"}"
 }
 
 ___x_cmd_ws___exe_default_sync(){
-    ___x_cmd_ws___exe_default_pull && ___x_cmd_ws___exe_default_push
+    ___x_cmd_ws___exe_default_pull && ___x_cmd_ws___exe_default_push "$@"
 }
